services:
  wordpress:
    image: wordpress:6.5.5-php8.3-apache
    restart: always
    ports:
      - ${WP_PORT:-8080}:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
      - ./volumes/wordpress/themes:/var/www/html/wp-content/themes
      - ./volumes/wordpress/plugins:/var/www/html/wp-content/plugins

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db:/var/lib/mysql
      - ./volumes/mysql:/home

volumes:
  wordpress:
  db:
